#!/usr/bin/env bash
# scripts/git-setup.sh
# Git configuration factory — applies this full git setup to a new machine.
#
# Usage:
#   ./scripts/git-setup.sh
#   ./scripts/git-setup.sh --name "Your Name" --email "your@email.com"
#
# What it does:
#   1. Creates ~/.config/git/{github,bitbucket}/ directory structure
#   2. Writes main config, per-host configs, global gitignore
#   3. Generates ~/.ssh/id_ed25519 (ed25519) if it doesn't exist
#   4. Configures SSH commit/tag signing (Git 2.34+, no GPG required)
#   5. Creates allowed_signers for local signature verification
#   6. Prints next steps for registering the key on GitHub/Bitbucket
#
# Idempotent: safe to run multiple times. Overwrites config files each run.

set -euo pipefail

# =============================================================================
# ARGUMENTS
# =============================================================================
GIT_NAME=""
GIT_EMAIL=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --name)   GIT_NAME="$2";  shift 2 ;;
    --email)  GIT_EMAIL="$2"; shift 2 ;;
    *) printf "Unknown option: %s\n" "$1" >&2; exit 1 ;;
  esac
done

prompt() {
  local var="$1" label="$2" default="$3"
  if [[ -z "${!var}" ]]; then
    printf "%s [%s]: " "$label" "$default"
    read -r "$var"
    [[ -z "${!var}" ]] && printf -v "$var" '%s' "$default"
  fi
}

prompt GIT_NAME   "Git name"  ""
prompt GIT_EMAIL  "Git email" ""

# Validate required fields
if [[ -z "$GIT_NAME" ]]; then
  printf "Error: Git name is required\n" >&2
  exit 1
fi
if [[ -z "$GIT_EMAIL" ]]; then
  printf "Error: Git email is required\n" >&2
  exit 1
fi

# =============================================================================
# PATHS
# =============================================================================
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
GIT_DIR="$XDG_CONFIG_HOME/git"
SSH_KEY="$HOME/.ssh/id_ed25519"

mkdir -p "$GIT_DIR/github" "$GIT_DIR/bitbucket" "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

# =============================================================================
# SSH SIGNING KEY
# =============================================================================
if [[ ! -f "$SSH_KEY" ]]; then
  printf "Generating SSH key for git signing...\n"
  ssh-keygen -t ed25519 -C "$GIT_EMAIL" -f "$SSH_KEY" -N "" || {
    printf "Error: Failed to generate SSH key\n" >&2
    exit 1
  }
  chmod 600 "$SSH_KEY"
else
  printf "SSH key already exists: %s\n" "$SSH_KEY"
fi

if [[ ! -f "${SSH_KEY}.pub" ]]; then
  printf "Error: SSH public key not found at %s\n" "${SSH_KEY}.pub" >&2
  exit 1
fi

SSH_PUB=$(cat "${SSH_KEY}.pub") || {
  printf "Error: Failed to read SSH public key\n" >&2
  exit 1
}

# allowed_signers — used by `git verify-commit` for local verification
printf "%s %s\n" "$GIT_EMAIL" "$SSH_PUB" > "$GIT_DIR/allowed_signers"

# =============================================================================
# GLOBAL GITIGNORE
# =============================================================================
cat > "$GIT_DIR/ignore" << 'EOF'
.DS_Store
Thumbs.db

.vscode
dist
node_modules
vendor

.env
*.log

**/.claude/settings.local.json
EOF

# =============================================================================
# GITHUB PER-HOST CONFIG
# =============================================================================
cat > "$GIT_DIR/github/.gitconfig" << EOF
[user]
  # SSH key used for both authentication and commit/tag signing.
  # Register on GitHub: Settings → SSH and GPG keys
  #   - Add once as Authentication Key  (enables passwordless push)
  #   - Add once as Signing Key         (shows "Verified" badge on commits)
  #
  # Via CLI (requires admin:public_key + admin:ssh_signing_key scopes):
  #   gh auth refresh -s admin:public_key,admin:ssh_signing_key
  #   gh ssh-key add ~/.ssh/id_ed25519.pub --title "\$(hostname)" --type authentication
  #   gh ssh-key add ~/.ssh/id_ed25519.pub --title "\$(hostname)" --type signing
	signingKey = ~/.ssh/id_ed25519.pub
	name = $GIT_NAME
	email = $GIT_EMAIL
EOF

# =============================================================================
# BITBUCKET PER-HOST CONFIG
# =============================================================================
cat > "$GIT_DIR/bitbucket/.gitconfig" << EOF
[user]
  # SSH key used for commit/tag signing (same key as GitHub).
  # Register on Bitbucket: Personal settings → SSH keys
	signingKey = ~/.ssh/id_ed25519.pub
	name = $GIT_NAME
	email = $GIT_EMAIL
EOF

# =============================================================================
# MAIN GIT CONFIG
# Write template first (literal, no shell expansion), then inject personal values.
# =============================================================================
cat > "$GIT_DIR/config" << 'CONFIG_EOF'
# ═══════════════════════════════════════════════════════════════════════════════
# GIT CONFIGURATION — macOS
# ═══════════════════════════════════════════════════════════════════════════════
# Generated by git-setup.sh; __CORES__ placeholders are filled with the
# machine's CPU core count at generation time.
# ═══════════════════════════════════════════════════════════════════════════════

[advice]
	detachedHead = false
[core]
	abbrev = 12
	autocrlf = input
	# editor intentionally NOT set — git falls back to $VISUAL/$EDITOR,
	# which .zprofile resolves with fallbacks (code → nvim → vim → nano)
	excludesFile = ~/.config/git/ignore
	filemode = true
	# Native FSEvents monitoring on APFS — big speedup for `git status` in large repos
	fsmonitor = true
	pager = delta
	preloadindex = true
	quotePath = false
	safeCRLF = warn
	sparseCheckout = true
	untrackedCache = true
	whitespace = fix,-indent-with-non-tab,trailing-space,cr-at-eol
[branch]
	autoSetupRebase = always
	sort = -committerdate
[help]
	autoCorrect = 10 # 1 second delay
[init]
	defaultBranch = main
[log]
	abbrevCommit = true
	date = iso
	follow = true
	showSignature = false
[maintenance]
	auto = true
	autodetach = true
	strategy = incremental
[maintenance "runMaintenance"]
	schedule = daily
[pull]
	rebase = merges
[blame]
	coloring = highlightRecent
	date = relative
[rebase]
	abbreviateCommands = true
	autoSquash = true
	autoStash = true
	updateRefs = true
[color]
	ui = true
[color "branch"]
	current = yellow reverse
	local = yellow
	remote = green
[color "status"]
	added = yellow
	changed = green
	untracked = cyan
[column]
	ui = auto
[diff]
	algorithm = histogram
	colorMoved = default
	indentHeuristic = true
	mnemonicPrefix = true
	renames = copies
	tool = default-difftool
	wordRegex = [^[:space:]]
[difftool]
	prompt = false
[fetch]
	parallel = __CORES__
	prune = true
	pruneTags = true
	writeCommitGraph = true
[gc]
	autodetach = true
	cruftPacks = true
[grep]
	column = true
	fullName = true
	lineNumber = true
[interactive]
	diffFilter = delta --color-only
	singleKey = true
[pack]
	writeReverseIndex = true
[revert]
	reference = true
[index]
	threads = __CORES__
[status]
	aheadBehind = true
	showUntrackedFiles = all
[tag]
	gpgSign = true
	sort = version:refname
[transfer]
	fsckObjects = true
[merge]
	autoStash = true
	conflictStyle = zdiff3
	ff = only
	tool = code
[mergetool]
	prompt = false
[push]
	autoSetupRemote = true
	default = simple
	followTags = true
	gpgSign = if-asked
	useForceIfIncludes = true
[rerere]
	autoUpdate = true
	enabled = true
[url "https://github.com/"]
	insteadOf = gh:
[delta]
	commit-decoration-style = bold yellow box ul
	commit-style = raw
	features = side-by-side-if-terminal-wide
	file-decoration-style = bold yellow ul box
	file-style = bold yellow ul
	hunk-header-decoration-style = yellow box
	hunk-header-file-style = bold yellow
	hunk-header-line-number-style = bold magenta
	hunk-header-style = file line-number syntax
	line-numbers = true
	line-numbers-left-format = " {nm:>4} │ "
	line-numbers-minus-style = brightred
	line-numbers-plus-style = brightgreen
	line-numbers-right-format = " {np:>4} │ "
	line-numbers-zero-style = brightblack
	minus-emph-style = syntax bold "#6f0000"
	minus-style = syntax "#340001"
	navigate = true
	paging = always
	plus-emph-style = syntax bold "#005500"
	plus-style = syntax "#012800"
	side-by-side = false
	syntax-theme = TwoDark
	true-color = always
	whitespace-error-style = 22 reverse
[diff "exif"]
	textconv = exiftool
[checkout]
	defaultRemote = origin
[commit]
	cleanup = scissors
	gpgSign = true
	verbose = true
[difftool "default-difftool"]
	cmd = code --wait --diff $LOCAL $REMOTE
[mergetool "code"]
	cmd = code --wait --merge $REMOTE $LOCAL $BASE $MERGED
# Per-host identity selection happens via the [includeIf] blocks at the
# BOTTOM of this file (they must come after [user] to override it).
[alias]
	# ━━━━━━ CONFIG ━━━━━━
	alias = "!f() { git config --get-regexp '^alias\\.' | sed 's/alias\\.//' | sort; }; f"
	conf = "!f() { git config --global --edit && echo '✓ Config saved'; }; f"
	whoami = "!f() { printf '\\n%b\\n' '\\033[1;36m━━ Git Configuration ━━\\033[0m'; printf '%b %s\\n' '\\033[1;32m✓\\033[0m Name:' \"$(git config user.name)\"; printf '%b %s\\n' '\\033[1;32m✓\\033[0m Email:' \"$(git config user.email)\"; printf '%b %s\\n' '\\033[1;32m✓\\033[0m Signing key:' \"$(git config user.signingkey)\"; printf '%b\\n\\n' '\\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m'; }; f"
	# ━━━━━━ STAGING ━━━━━━
	addp = add --patch
	add-all = add --all
	unstage = restore --staged
	discard = "!f() { echo '⚠️  Files to discard:'; git diff --name-only; read -p 'Continue? (y/n) ' -n 1; echo; [[ $REPLY == 'y' ]] && git restore --worktree || echo '❌ Cancelled'; }; f"
	review = "!git diff --cached --color=always | delta"
	st = "!git status --short --branch --color=always"
	# ━━━━━━ COMMITS ━━━━━━
	ac = "!git add --all && git commit --verbose"
	acm = "!f() { git add --all && git commit -m \"$1\"; }; f"
	scope = "!f() { git commit -m \"$1($2): $3\"; }; f"
	edit-last = commit --amend --no-verify
	mnd = commit --all --amend --no-edit
	amend = commit --amend --reuse-message=HEAD
	recommit = commit --amend -m
	undo = reset --soft HEAD~1
	wip = "!git add -A && git commit -m 'WIP: work in progress'"
	fixup = "!f() { git commit --fixup \"$1\"; }; f"
	autofixup = "!upstream=$(git rev-parse --abbrev-ref @{u} 2>/dev/null || echo 'origin/main'); git rebase -i --autosquash \"$upstream\""
	impact = "!git diff --cached --numstat | awk '{added+=$1; removed+=$2} END {print \"Lines added: \" added \", Lines removed: \" removed}'"
	# ━━━━━━ BRANCHES ━━━━━━
	br = branch
	bra = branch --all
	brd = branch --delete
	brv = branch --verbose --verbose
	current = branch --show-current
	fresh = "!f() { git checkout -b \"$1\" && git push -u origin \"$1\"; }; f"
	recent = "!git for-each-ref --sort=-committerdate refs/heads --format='%(refname:short) %(committerdate:relative)' | head -15"
	stale = "!git branch --sort=committerdate --format='%(committerdate:relative)%09%(refname:short)' | tail -15"
	# ━━━━━━ REBASE ━━━━━━
	rebase-onto = "!f() { git rebase --onto ${1-main} ${2-main}; }; f"
	rebase-main = "!git fetch origin main && git rebase origin/main"
	reb = "!r() { git rebase --interactive HEAD~$1; }; r"
	rebase-branch = "!f() { git rebase --interactive $(git merge-base HEAD ${1-main}); }; f"
	resign = "!r() { git rebase --interactive HEAD~${1:-10} --exec \"git commit --amend -S --no-edit --no-verify\"; }; r"
	cont = rebase --continue
	# ━━━━━━ MERGE ━━━━━━
	mff = merge --no-ff
	mmsg = merge --no-edit
	# ━━━━━━ PUSH/FETCH ━━━━━━
	fp = fetch --all --prune
	sync = "!upstream=$(git rev-parse --abbrev-ref @{u} 2>/dev/null || echo 'origin/main'); git fetch && git rebase \"$upstream\""
	pushf = push --force-with-lease --force-if-includes
	undo-push = "!git push --force-with-lease origin HEAD~1:$(git branch --show-current)"
	promi = "!r() { git pull --rebase=interactive origin ${1-main}; }; r"
	# ━━━━━━ STASH ━━━━━━
	stashk = stash push --keep-index
	stash-all = stash push --include-untracked
	stash-list = stash list --format="%C(yellow)%gd%C(reset) %s"
	# ━━━━━━ LOG & HISTORY ━━━━━━
	lg = log --graph --abbrev-commit --decorate --all --date=relative --format=format:'%C(bold blue)%h%C(reset) %C(bold yellow)%d%C(reset) %C(white)%s%C(reset) %C(bold cyan)(%an)%C(reset) %C(bold green)(%ar)%C(reset)'
	lga = log --graph --abbrev-commit --decorate --all --date=relative --format=format:'%C(bold blue)%h%C(reset)%C(bold yellow)%d%C(reset) %C(white)%s%C(reset) %C(bold green)(%ar)%C(reset)'
	log-summary = log --oneline --graph --decorate --all
	what = log --oneline -n 10
	new = log --graph main..HEAD --oneline
	missing = log --graph HEAD..main --oneline
	ahead = log main..HEAD --oneline
	behind = log HEAD..main --oneline
	commits-today = log --since=today --oneline
	commits-week = "!git log --since='1 week ago' --oneline"
	commits-since = "!f() { git log --since=\"$1\" --oneline --all; }; f"
	changed = show --name-status
	mine = "!git log --author=\"$(git config user.name)\" --oneline"
	# ━━━━━━ SEARCH ━━━━━━
	find-commit = log --oneline --grep
	find-author = log --oneline --author
	find-file = log --oneline --name-only
	find-deleted = log --oneline --diff-filter=D --summary
	find-deleted-line = "!f() { git log -p -S \"$1\" --all | head -100; }; f"
	find-function = "!f() { git log -p --all -G \"(def|function) $1\" -- '*.js' '*.go' '*.php' '*.ts'; }; f"
	# ━━━━━━ DIFF ━━━━━━
	diff-tool = difftool --dir-diff
	diff-main = "!git diff origin/main...HEAD --stat"
	staged-files = diff --cached --name-only
	unstaged-files = diff --name-only
	all-changes = diff HEAD --name-only
	# ━━━━━━ BLAME ━━━━━━
	blame-line = "!f() { git blame -L ${2:-1},${3:-1} \"${1:-.}\"; }; f"
	hotspots = "!git log --pretty=format: --name-only --diff-filter=d | sort | uniq -c | sort -rn | head -20"
	# ━━━━━━ RESET & RECOVERY ━━━━━━
	reset-soft = reset --soft
	reset-hard = "!f() { echo '🚨 This will discard all changes'; read -p 'Type YES to confirm: ' confirm; [[ $confirm == 'YES' ]] && git reset --hard || echo '❌ Cancelled'; }; f"
	restore-file = "!f() { git checkout HEAD -- \"$1\"; }; f"
	untrack = "!f() { git rm --cached \"$1\" && echo \"✓ Untracked: $1\"; }; f"
	root = rev-list --max-parents=0 HEAD
	# ━━━━━━ CHERRY-PICK ━━━━━━
	pick = cherry-pick --no-commit
	# ━━━━━━ MAINTENANCE ━━━━━━
	cleanup = "!f() { echo '🧹 Cleaning merged branches...'; git branch --merged main | grep -v '* main' | xargs -r git branch -d; echo '✅ Done'; }; f"
	gc-aggressive = gc --aggressive --prune=now
	bootstrap = "!f() { echo \"🚀 Bootstrapping new Git repository...\"; git init || return 1; git maintenance register || return 1; git maintenance start || return 1; git commit --allow-empty --message 'chore: initial commit' $(git config --get commit.gpgsign | grep -q true && echo '-S') || return 1; echo \"✅ Repository bootstrap complete!\"; }; f"
	# ━━━━━━ STATISTICS ━━━━━━
	stats = log --stat --oneline
	authors = log --format='%aN' | sort | uniq -c | sort -rn
	top-authors = "!git shortlog -sn --all | head -10"
	contributors = shortlog -sn
	lines-changed = log --format=medium --numstat
	# ━━━━━━ MONOREPO ━━━━━━
	workspace = "!f() { cd packages/$1 && git status; }; f"
	affected = "!git diff origin/main...HEAD --name-only | grep -o 'packages/[^/]*' | sort -u"
	packages-changed = "!git diff --name-only | cut -d'/' -f2 | sort -u"
[user]
	signingKey = ~/.ssh/id_ed25519.pub
	name = __GIT_NAME__
	email = __GIT_EMAIL__
[gpg]
	format = ssh
[gpg "ssh"]
	allowedSignersFile = ~/.config/git/allowed_signers
[filter "lfs"]
	clean = git-lfs clean -- %f
	process = git-lfs filter-process
	required = true
	smudge = git-lfs smudge -- %f
# Per-host identities: repos under $CODE_DIR/<host>/ pick up the matching
# config (name/email/signingKey overrides). Trailing / matches recursively.
# These come LAST so they override the [user] defaults above.
# If you change CODE_DIR in modules/local.zsh, update these paths to match.
[includeIf "gitdir:~/Developer/github/"]
	path = ~/.config/git/github/.gitconfig
[includeIf "gitdir:~/Developer/bitbucket/"]
	path = ~/.config/git/bitbucket/.gitconfig
CONFIG_EOF

# Inject personal values and CPU core count
# (sed delimiter | avoids conflicts with path slashes)
CORES=$(sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 8)
sed -i.bak \
  -e "s|__GIT_NAME__|$GIT_NAME|g" \
  -e "s|__GIT_EMAIL__|$GIT_EMAIL|g" \
  -e "s|__CORES__|$CORES|g" \
  "$GIT_DIR/config" || {
  printf "Error: Failed to configure git settings\n" >&2
  exit 1
}
rm -f "$GIT_DIR/config.bak"
printf "Set fetch/index parallelism to %s cores\n" "$CORES"

# =============================================================================
# GITHUB CREDENTIAL HELPER (gh CLI)
# Write directly to $GIT_DIR/config instead of --global, because GIT_CONFIG_GLOBAL
# may not be set yet when this script runs (it is set by .zprofile at login time).
# Using --global here would write to ~/.gitconfig and conflict with the XDG config.
# =============================================================================
GH_BIN=$(command -v gh 2>/dev/null || true)
if [[ -n "$GH_BIN" ]]; then
  git config --file "$GIT_DIR/config" credential."https://github.com".helper "" || true
  git config --file "$GIT_DIR/config" --add credential."https://github.com".helper "!$GH_BIN auth git-credential" || {
    printf "Warning: Failed to configure GitHub credential helper\n" >&2
  }
  git config --file "$GIT_DIR/config" credential."https://gist.github.com".helper "" || true
  git config --file "$GIT_DIR/config" --add credential."https://gist.github.com".helper "!$GH_BIN auth git-credential" || {
    printf "Warning: Failed to configure Gist credential helper\n" >&2
  }
fi

# =============================================================================
# NEXT STEPS
# =============================================================================
printf "\n✅ Git configuration applied to %s\n\n" "$GIT_DIR"
printf "📋 Next steps:\n"
printf "   1. Register SSH key on GitHub (shows 'Verified' badge on commits):\n"
printf "      gh auth refresh -s admin:public_key,admin:ssh_signing_key\n"
printf "      gh ssh-key add ~/.ssh/id_ed25519.pub --title \"%s\" --type authentication\n" "$(hostname)"
printf "      gh ssh-key add ~/.ssh/id_ed25519.pub --title \"%s\" --type signing\n\n" "$(hostname)"
printf "   2. Verify signing works:\n"
printf "      git commit --allow-empty -S -m 'test: ssh signing'\n"
printf "      git log --show-signature -1\n\n"
printf "   3. Set GIT_CONFIG_GLOBAL in your shell profile (~/.config/zsh/.zprofile):\n"
printf "      export GIT_CONFIG_GLOBAL=\"\$HOME/.config/git/config\"\n\n"
printf "   Public key:\n"
printf "      %s\n" "$SSH_PUB"
